use_frameworks!

source  'https://github.com/yanjian/PrivatePods.git'
source  'https://github.com/CocoaPods/Specs.git' #官方的资源 ---- 默认行为...

target 'ATest_Example' do
  pod 'ATest', :path => '../'
  pod 'BTest_Categoty'
  
end
