use_frameworks!

target 'ATest_Example' do
  pod 'ATest', :path => '../'

  target 'ATest_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
